version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install Test Dependencies
          command: pip install -r requirements.txt  # Ensure you have a requirements file
      - run:
          name: Run Unittest
          command: python -m unittest discover -s tests -p "*.py"  # Adjust according to your test folder structure
      - store_test_results:
          path: test-results  # You need to specify a path to store test results

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-python
    # - deploy:
    #     requires:
    #       - test-python
