version: 2.1

orbs:
  python: circleci/python@2

jobs:
  build-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install Build Dependencies
          command: pip install build  # This installs the `build` tool to create packages
      - run:
          name: Build Package
          command: python -m build  # This will create a distribution under `dist/`
      - store_artifacts:
          path: dist  # Store the built package as an artifact

  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install Test Dependencies
          command: pip install -r requirements.txt  # Ensure you have a requirements file
      - run:
          name: Run Unittest
          command: python -m unittest discover -s tests -p "*.py"  # Adjust according to your test folder structure
      - store_test_results:
          path: test-results  # Store test results
      - store_artifacts:
          path: test-results  # Store the test results as artifacts as well

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - build-python
      - test-python
    # - deploy:
    #     requires:
    #       - build-python
    #       - test-python
