version: 2.1
orbs:
  python: circleci/python@2  # Official CircleCI Python orb
  # po: fernfernfern/python-orb@0.0.10  # External orb for Python jobs
  #build: orbs/build-python/orb.yml
  #testing: orbs/testing-python/orb.yml 

jobs:
  build-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages  # Using the Python orb to install packages from requirements.txt
      - run:
          name: Install Build Dependencies
          command: pip install build  # This installs the build tool to create packages
      - run:
          name: Build Package
          command: python -m build  # This will create a distribution under dist/
      - store_artifacts:
          path: dist  # Store the built package as an artifact

  test-python:  # Correct indentation here
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages  # Using the Python orb to install packages from requirements.txt
      - run:
          name: Install Test and Coverage Dependencies
          command: |
            pip install coverage  # Install coverage for tracking test coverage
      - run:
          name: Run Unit Tests and Coverage
          command: |
            coverage run -m unittest discover -s tests -p "*.py"  # Run tests with coverage
            coverage xml  # Generate coverage XML report
            coverage html  # Generate HTML coverage report
      - store_test_results:
          path: test-results  # Store test results (make sure to create this directory if it doesn't exist)
      - store_artifacts:
          path: coverage.xml  # Store the coverage XML report as an artifact
      - store_artifacts:
          path: htmlcov  # Store the HTML coverage report directory as an artifact

workflows:
  build-and-test:
    jobs:
      - build-python
      - test-python
